apiVersion: v1
kind: Service
metadata:
  labels:
     app: devconnectorapp
  name: devconnectorapp
  namespace: dev-connector
spec:
  type: LoadBalancer
  ports:
  - name: "dev-connector-service"
    port: 3000
    targetPort: 3000
  selector:
    app: devconnectorapp
